modLoader="javafml"
loaderVersion="[48,)"
issueTrackerURL="https://github.com/3arthqu4ke/hmc-optimizations"
license = "MIT"

[[mods]]
modId = "hmc_optimizations"
version = "${version}"
displayName = "HMC-Optimizations"
authors = "3arthqu4ke"
description = '''
    Version specific optimizations for HeadlessMC
'''

[[dependencies.hmc_optimizations]]
modId="minecraft"
mandatory=true
versionRange="[1.20.4]"
ordering="NONE"
side="BOTH"
