name: Build All
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        version:
          - { dir: 1_21, mc: 1.21.3, lex: 53.0.7, neo: 11-beta, java: 21 }
          - { dir: 1_21, mc: 1.21.1, lex: 52.0.2, neo: 4, java: 21 }
          #- { dir: 1_21, mc: 1.21, lex: 51.0.24, neo: 96-beta, java: 21 }
          - { dir: 1_20, mc: 1.20.6, lex: 50.1.10, neo: 119, java: 21 }
          - { dir: 1_19, mc: 1.19.4, lex: 45.2.9, neo: 0, java: 17 }
          - { dir: 1_16, mc: 1.16.5, lex: 36.2.42, neo: 0, java: 8 }
          - { dir: 1_12, mc: 1.12.2, lex: 14.23.5.2860, neo: 0, java: 8 }
    uses: 3arthqu4ke/hmc-optimizations/.github/workflows/build-specific-reusable.yml@main
    with:
      dir: ${{ matrix.version.dir }}
      mc: ${{ matrix.version.mc }}
      lex: ${{ matrix.version.lex }}
      neo: ${{ matrix.version.neo }}
      java: ${{ matrix.version.java }}
      