name: Build All
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        version:
          - { dir: 1.21, mc: 1.21.1, lex: 52.0.2, neo: 4, java: 21 }
          - { dir: 1.21, mc: 1.21, lex: 51.0.24, neo: 96-beta, java: 21 }
    uses: 3arthqu4ke/hmc-optimizations/.github/workflows/build-specific-reusable.yml@main
    with:
      dir: ${{ matrix.version.dir }}
      mc: ${{ matrix.version.mc }}
      lex: ${{ matrix.version.lex }}
      neo: ${{ matrix.version.neo }}
      java: ${{ matrix.version.java }}
      