name: Release
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v2
                with:
                    java-version: 17
                    distribution: adopt
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Build
                run: ./gradlew build
            -   name: Release
                uses: softprops/action-gh-release@v2
                with:
                  files: build/libs/*
    
