name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
    build:
        strategy:
            matrix:
                version:
                    - { dir: 1_21, mc: 1.21.1, lex: 52.0.2, neo: 4, java: 21 }
                    - { dir: 1_21, mc: 1.21, lex: 51.0.24, neo: 96-beta, java: 21 }
                    - { dir: 1_20, mc: 1.20.6, lex: 50.1.10, neo: 119, java: 21 }
                    - { dir: 1_19, mc: 1.19.4, lex: 45.2.9, neo: 0, java: 17 }
                    - { dir: 1_12, mc: 1.12.2, lex: 14.23.5.2860, neo: 0, java: 8 }
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: ${{ matrix.version.java }}
                  distribution: temurin
            - name: Grant execute permission for gradlew
              working-directory: ./${{ matrix.version.dir }}
              run: chmod +x gradlew
            - name: Build
              working-directory: ./${{ matrix.version.dir }}
              run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }} -Pneoforge_version=${{ matrix.version.neo }} --stacktrace
            - name: Delete dev jar
              run: rm ./${{ matrix.version.dir }}/build/libs/*-dev.jar
            - name: Upload ${{ matrix.version.mc }} Jars
              uses: actions/upload-artifact@v4
              with:
                  name: jars-${{ matrix.version.mc }}
                  path: ./${{ matrix.version.dir }}/build/libs/*.jar

    merge:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Merge Artifacts
          uses: actions/upload-artifact/merge@v4
          with:
            delete-merged: true

    release:
        runs-on: ubuntu-latest
        needs: merge
        steps:
          - uses: actions/download-artifact@v4
          - name: Display structure of downloaded files
            run: ls -R
          - name: Release
            uses: softprops/action-gh-release@v2
            if: startsWith(github.ref, 'refs/tags/')
            with:
              generate_release_notes: true
              files: |
                ./merged-artifacts/*.jar
