name: Run all versions with mc-runtime-test
on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:

jobs:
  run:
    strategy:
      matrix:
        version:
          - { dir: 1_21, mc: 1.21.4, java: 21, lex: 54.0.17, neo: 70-beta, type: neoforge, modloader: neoforge, regex: .*neoforge.* }
          - { dir: 1_21, mc: 1.21.4, java: 21, lex: 54.0.17, neo: 70-beta, type: lexforge, modloader: forge, regex: .*forge.* }
          - { dir: 1_21, mc: 1.21.4, java: 21, lex: 54.0.17, neo: 70-beta, fabric, modloader: fabric, regex: .*fabric.* }
          - { dir: 1_21, mc: 1.21.3, java: 21, lex: 53.0.7, neo: 11-beta, type: neoforge, modloader: neoforge, regex: .*neoforge.* }
          - { dir: 1_21, mc: 1.21.3, java: 21, lex: 53.0.7, neo: 11-beta, type: lexforge, modloader: forge, regex: .*forge.* }
          - { dir: 1_21, mc: 1.21.3, java: 21, lex: 53.0.7, neo: 11-beta, fabric, modloader: fabric, regex: .*fabric.* }
          - { dir: 1_21, mc: 1.21.1, java: 21, lex: 52.0.2, neo: 4, type: neoforge, modloader: neoforge, regex: .*neoforge.* }
          - { dir: 1_21, mc: 1.21.1, java: 21, lex: 52.0.2, neo: 4, type: lexforge, modloader: forge, regex: .*forge.* }
          - { dir: 1_21, mc: 1.21.1, java: 21, lex: 52.0.2, neo: 4, fabric, modloader: fabric, regex: .*fabric.* }
          #- { dir: 1_21, mc: 1.21, java: 21, lex: 51.0.24, neo: 96-beta, type: neoforge, modloader: neoforge, regex: .*neoforge.* }
          #- { dir: 1_21, mc: 1.21, java: 21, lex: 51.0.24, neo: 96-beta, type: lexforge, modloader: forge, regex: .*forge.* }
          #- { dir: 1_21, mc: 1.21, java: 21, lex: 51.0.24, neo: 96-beta, fabric, modloader: fabric, regex: .*fabric.* }
          - { dir: 1_20, mc: 1.20.6, java: 21, lex: 50.1.10, neo: 119, type: neoforge, modloader: neoforge, regex: .*neoforge.* }
          - { dir: 1_20, mc: 1.20.6, java: 21, lex: 50.1.10, neo: 119, type: lexforge, modloader: forge, regex: .*forge.* }
          - { dir: 1_20, mc: 1.20.6, java: 21, lex: 50.1.10, neo: 119, fabric, modloader: fabric, regex: .*fabric.* }
          - { dir: 1_19, mc: 1.19.4, java: 17, lex: 45.2.9, neo: 0, type: lexforge, modloader: forge, regex: .*forge.* }
          - { dir: 1_19, mc: 1.19.4, java: 17, lex: 45.2.9, neo: 0, fabric, modloader: fabric, regex: .*fabric.* }
          - { dir: 1_16, mc: 1.16.5, java: 8, lex: 36.2.42, neo: 0, type: lexforge, modloader: forge, regex: .*forge.* }
          - { dir: 1_16, mc: 1.16.5, java: 8, lex: 36.2.42, neo: 0, fabric, modloader: fabric, regex: .*fabric.* }
          - { dir: 1_12, mc: 1.12.2, java: 8, lex: 14.23.5.2860, neo: 0, type: lexforge, modloader: forge, regex: .*forge.* }
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Grant execute permission for gradlew
        working-directory: ./${{ matrix.version.dir }}
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ./${{ matrix.version.dir }}
        run: ./gradlew build -Pminecraft_version=${{ matrix.version.mc }} -Plexforge_version=${{ matrix.version.lex }} -Pneoforge_version=${{ matrix.version.neo }} --stacktrace
      - name: Create mods dir
        run: mkdir -p run/mods
      - name: List mod files
        run: ls ${{ matrix.version.dir }}/build/libs
      - name: Delete dev jar
        run: rm ${{ matrix.version.dir }}/build/libs/*-dev.jar
      #- name: Delete remapped jar
      #  run: rm ${{ matrix.version.dir }}/build/libs/*-remapped.jar
      - name: Copy mod jar
        run: cp ${{ matrix.version.dir }}/build/libs/hmc-optimizations-*${{ matrix.version.type }}*.jar run/mods
      - name: List mod dir
        run: ls run/mods
      - name: Run the MC client
        uses: 3arthqu4ke/mc-runtime-test@3.0.0
        with:
          mc: ${{ matrix.version.mc }}
          modloader: ${{ matrix.version.modloader }}
          regex: ${{ matrix.version.regex }}
          java: ${{ matrix.version.java }}
          mc-runtime-test: ${{ matrix.version.type }}
          xvfb: false
          headlessmc-command: -lwjgl --retries 3 --jvm -Djava.awt.headless=true
