name: Run the Fabric MC client
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Copy mod jar to mods
        run: cp -r build/libs/hmc-optimizations-*-fabric.jar run/mods/
      - name: List mods
        run: ls run/mods
      - name: Run the MC client
        uses: 3arthqu4ke/mc-runtime-test@1.0.0
        with:
          mc: 1.20.4
          modloader: fabric
          regex: .*fabric.*
          java: 17
